name: job-listing-backend

version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_ORIGIN_PRODUCTION=${ALLOWED_ORIGIN_PRODUCTION}
      - ALLOWED_ORIGIN_DEVELOPMENT=${ALLOWED_ORIGIN_DEVELOPMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_URL=${OPENROUTER_URL}
    env_file:
      - .env
